server:
  port: 8082

api:
  external-service-host: ${ECHO_ENDPOINT:localhost}
  external-service-port: ${ECHO_PORT:8081}

security:
  user:
    name: ${SECRET_USERNAME:test}
    password: ${SECRET_PASSWORD:test}