# Deployment only for Caller Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  # This is a ReplicaSet configuration
  replicas: 1
  selector:
    matchLabels:
      app: back-end
  # This is a template for a Pod
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        # Now we have only one container of caller-service in our deployment
        - name: caller-service
          image: caller-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "500M"
              cpu: "250m"
          # Here we are setting up an environment variables
          # for our container
          env:
            - name: ECHO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: external.host
                  name: caller-service-config
            - name: ECHO_PORT
              valueFrom:
                configMapKeyRef:
                  key: external.port
                  name: caller-service-config
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  key: spring.user.name
                  name: spring-secrets
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: spring.user.password
                  name: spring-secrets

# Deployment for Echo Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    app: echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service-pod
  template:
    metadata:
      labels:
        app: echo-service-pod
    spec:
      containers:
        - name: echo-service
          image: echo-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "500M"
              cpu: "250m"
---
# NodePort service for caller-service which is our back-end
apiVersion: v1
kind: Service
metadata:
  name: backend-node-port
spec:
  type: NodePort
  selector:
    app: back-end
  ports:
    - port: 8082

---
# NodePort service for echo-service
apiVersion: v1
kind: Service
metadata:
  name: echo-node-port
spec:
  type: NodePort
  selector:
    app: echo-service-pod
  ports:
    - port: 8081
---
# Ingress configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-node-port
                port:
                  number: 8082
---
apiVersion: v1
kind: Secret
stringData:
  spring.user.name: secret_username
  spring.user.password: s3cr3t_!Pa$$w0rd!
metadata:
  name: spring-secrets

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caller-service-config
data:
  external.host: "echo-node-port"
  external.port: "8081"