apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  # This is a ReplicaSet configuration
  replicas: 1
  selector:
    matchLabels:
      app: back-end
  # This is a template for a Pod
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:

        - name: caller-service
          image: caller-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "500M"
              cpu: "250m"

        - name: echo-service
          image: echo-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "500M"
              cpu: "250m"
---
# NodePort configuration

apiVersion: v1
kind: Service
metadata:
  name: backend-node-port
spec:
  type: NodePort
  selector:
    app: back-end
  ports:
    - port: 8082

---
# Ingress configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-node-port
                port:
                  number: 8082